services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: agent_pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "132157"
      POSTGRES_DB: agent_db
    ports:
      - "5432:5432"
    volumes:
      - ./script/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: