// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.32.1
// source: core_agent.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	CoreAgent_Chat_FullMethodName         = "/core_agent.CoreAgent/Chat"
	CoreAgent_GetAgentList_FullMethodName = "/core_agent.CoreAgent/GetAgentList"
	CoreAgent_ExecutePlan_FullMethodName  = "/core_agent.CoreAgent/ExecutePlan"
	CoreAgent_StopRun_FullMethodName      = "/core_agent.CoreAgent/StopRun"
	CoreAgent_EvaluateRAG_FullMethodName  = "/core_agent.CoreAgent/EvaluateRAG"
)

// CoreAgentClient is the client API for CoreAgent service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreAgentClient interface {
	Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatResponse], error)
	GetAgentList(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentListResponse], error)
	ExecutePlan(ctx context.Context, in *ExecutePlanRequest, opts ...grpc.CallOption) (*ExecutePlanResponse, error)
	// StopRun acknowledges a cooperative stop request for an execution run.
	StopRun(ctx context.Context, in *StopRunRequest, opts ...grpc.CallOption) (*StopRunResponse, error)
	EvaluateRAG(ctx context.Context, in *EvaluateRAGRequest, opts ...grpc.CallOption) (*EvaluateRAGResponse, error)
}

type coreAgentClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreAgentClient(cc grpc.ClientConnInterface) CoreAgentClient {
	return &coreAgentClient{cc}
}

func (c *coreAgentClient) Chat(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ChatResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoreAgent_ServiceDesc.Streams[0], CoreAgent_Chat_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, ChatResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoreAgent_ChatClient = grpc.ServerStreamingClient[ChatResponse]

func (c *coreAgentClient) GetAgentList(ctx context.Context, in *ChatRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[AgentListResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &CoreAgent_ServiceDesc.Streams[1], CoreAgent_GetAgentList_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ChatRequest, AgentListResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoreAgent_GetAgentListClient = grpc.ServerStreamingClient[AgentListResponse]

func (c *coreAgentClient) ExecutePlan(ctx context.Context, in *ExecutePlanRequest, opts ...grpc.CallOption) (*ExecutePlanResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecutePlanResponse)
	err := c.cc.Invoke(ctx, CoreAgent_ExecutePlan_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreAgentClient) StopRun(ctx context.Context, in *StopRunRequest, opts ...grpc.CallOption) (*StopRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopRunResponse)
	err := c.cc.Invoke(ctx, CoreAgent_StopRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *coreAgentClient) EvaluateRAG(ctx context.Context, in *EvaluateRAGRequest, opts ...grpc.CallOption) (*EvaluateRAGResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EvaluateRAGResponse)
	err := c.cc.Invoke(ctx, CoreAgent_EvaluateRAG_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreAgentServer is the server API for CoreAgent service.
// All implementations must embed UnimplementedCoreAgentServer
// for forward compatibility.
type CoreAgentServer interface {
	Chat(*ChatRequest, grpc.ServerStreamingServer[ChatResponse]) error
	GetAgentList(*ChatRequest, grpc.ServerStreamingServer[AgentListResponse]) error
	ExecutePlan(context.Context, *ExecutePlanRequest) (*ExecutePlanResponse, error)
	// StopRun acknowledges a cooperative stop request for an execution run.
	StopRun(context.Context, *StopRunRequest) (*StopRunResponse, error)
	EvaluateRAG(context.Context, *EvaluateRAGRequest) (*EvaluateRAGResponse, error)
	mustEmbedUnimplementedCoreAgentServer()
}

// UnimplementedCoreAgentServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreAgentServer struct{}

func (UnimplementedCoreAgentServer) Chat(*ChatRequest, grpc.ServerStreamingServer[ChatResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Chat not implemented")
}
func (UnimplementedCoreAgentServer) GetAgentList(*ChatRequest, grpc.ServerStreamingServer[AgentListResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetAgentList not implemented")
}
func (UnimplementedCoreAgentServer) ExecutePlan(context.Context, *ExecutePlanRequest) (*ExecutePlanResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecutePlan not implemented")
}
func (UnimplementedCoreAgentServer) StopRun(context.Context, *StopRunRequest) (*StopRunResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopRun not implemented")
}
func (UnimplementedCoreAgentServer) EvaluateRAG(context.Context, *EvaluateRAGRequest) (*EvaluateRAGResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateRAG not implemented")
}
func (UnimplementedCoreAgentServer) mustEmbedUnimplementedCoreAgentServer() {}
func (UnimplementedCoreAgentServer) testEmbeddedByValue()                   {}

// UnsafeCoreAgentServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreAgentServer will
// result in compilation errors.
type UnsafeCoreAgentServer interface {
	mustEmbedUnimplementedCoreAgentServer()
}

func RegisterCoreAgentServer(s grpc.ServiceRegistrar, srv CoreAgentServer) {
	// If the following call pancis, it indicates UnimplementedCoreAgentServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreAgent_ServiceDesc, srv)
}

func _CoreAgent_Chat_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoreAgentServer).Chat(m, &grpc.GenericServerStream[ChatRequest, ChatResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoreAgent_ChatServer = grpc.ServerStreamingServer[ChatResponse]

func _CoreAgent_GetAgentList_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(CoreAgentServer).GetAgentList(m, &grpc.GenericServerStream[ChatRequest, AgentListResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type CoreAgent_GetAgentListServer = grpc.ServerStreamingServer[AgentListResponse]

func _CoreAgent_ExecutePlan_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecutePlanRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreAgentServer).ExecutePlan(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreAgent_ExecutePlan_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreAgentServer).ExecutePlan(ctx, req.(*ExecutePlanRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreAgent_StopRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopRunRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreAgentServer).StopRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreAgent_StopRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreAgentServer).StopRun(ctx, req.(*StopRunRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _CoreAgent_EvaluateRAG_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EvaluateRAGRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreAgentServer).EvaluateRAG(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreAgent_EvaluateRAG_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreAgentServer).EvaluateRAG(ctx, req.(*EvaluateRAGRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreAgent_ServiceDesc is the grpc.ServiceDesc for CoreAgent service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreAgent_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "core_agent.CoreAgent",
	HandlerType: (*CoreAgentServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ExecutePlan",
			Handler:    _CoreAgent_ExecutePlan_Handler,
		},
		{
			MethodName: "StopRun",
			Handler:    _CoreAgent_StopRun_Handler,
		},
		{
			MethodName: "EvaluateRAG",
			Handler:    _CoreAgent_EvaluateRAG_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Chat",
			Handler:       _CoreAgent_Chat_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "GetAgentList",
			Handler:       _CoreAgent_GetAgentList_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "core_agent.proto",
}
