// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: core_agent.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	SessionId        string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	TargetAgentId    string                 `protobuf:"bytes,2,opt,name=target_agent_id,json=targetAgentId,proto3" json:"target_agent_id,omitempty"`
	Message          string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	PresentationMode string                 `protobuf:"bytes,4,opt,name=presentation_mode,json=presentationMode,proto3" json:"presentation_mode,omitempty"` // "workflow" | "chat" | "" (empty = ask before running)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ChatRequest) Reset() {
	*x = ChatRequest{}
	mi := &file_core_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatRequest) ProtoMessage() {}

func (x *ChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatRequest.ProtoReflect.Descriptor instead.
func (*ChatRequest) Descriptor() ([]byte, []int) {
	return file_core_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ChatRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatRequest) GetTargetAgentId() string {
	if x != nil {
		return x.TargetAgentId
	}
	return ""
}

func (x *ChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatRequest) GetPresentationMode() string {
	if x != nil {
		return x.PresentationMode
	}
	return ""
}

type AgentInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	Goal          string                 `protobuf:"bytes,3,opt,name=goal,proto3" json:"goal,omitempty"`
	Tools         []string               `protobuf:"bytes,4,rep,name=tools,proto3" json:"tools,omitempty"`
	Model         string                 `protobuf:"bytes,5,opt,name=model,proto3" json:"model,omitempty"` // OpenRouter model ID
	Order         int32                  `protobuf:"varint,6,opt,name=order,proto3" json:"order,omitempty"`
	IsLeader      bool                   `protobuf:"varint,7,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInfo) Reset() {
	*x = AgentInfo{}
	mi := &file_core_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInfo) ProtoMessage() {}

func (x *AgentInfo) ProtoReflect() protoreflect.Message {
	mi := &file_core_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInfo.ProtoReflect.Descriptor instead.
func (*AgentInfo) Descriptor() ([]byte, []int) {
	return file_core_agent_proto_rawDescGZIP(), []int{1}
}

func (x *AgentInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AgentInfo) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AgentInfo) GetGoal() string {
	if x != nil {
		return x.Goal
	}
	return ""
}

func (x *AgentInfo) GetTools() []string {
	if x != nil {
		return x.Tools
	}
	return nil
}

func (x *AgentInfo) GetModel() string {
	if x != nil {
		return x.Model
	}
	return ""
}

func (x *AgentInfo) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *AgentInfo) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

type PlanCreatedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PlanId        string                 `protobuf:"bytes,1,opt,name=plan_id,json=planId,proto3" json:"plan_id,omitempty"`
	Orchestration string                 `protobuf:"bytes,2,opt,name=orchestration,proto3" json:"orchestration,omitempty"`
	Agents        []*AgentInfo           `protobuf:"bytes,3,rep,name=agents,proto3" json:"agents,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PlanCreatedEvent) Reset() {
	*x = PlanCreatedEvent{}
	mi := &file_core_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanCreatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanCreatedEvent) ProtoMessage() {}

func (x *PlanCreatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_core_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanCreatedEvent.ProtoReflect.Descriptor instead.
func (*PlanCreatedEvent) Descriptor() ([]byte, []int) {
	return file_core_agent_proto_rawDescGZIP(), []int{2}
}

func (x *PlanCreatedEvent) GetPlanId() string {
	if x != nil {
		return x.PlanId
	}
	return ""
}

func (x *PlanCreatedEvent) GetOrchestration() string {
	if x != nil {
		return x.Orchestration
	}
	return ""
}

func (x *PlanCreatedEvent) GetAgents() []*AgentInfo {
	if x != nil {
		return x.Agents
	}
	return nil
}

type SessionRenamedEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionRenamedEvent) Reset() {
	*x = SessionRenamedEvent{}
	mi := &file_core_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionRenamedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionRenamedEvent) ProtoMessage() {}

func (x *SessionRenamedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_core_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionRenamedEvent.ProtoReflect.Descriptor instead.
func (*SessionRenamedEvent) Descriptor() ([]byte, []int) {
	return file_core_agent_proto_rawDescGZIP(), []int{3}
}

func (x *SessionRenamedEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionRenamedEvent) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

type TokenUsageEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	InputTokens   int32                  `protobuf:"varint,3,opt,name=input_tokens,json=inputTokens,proto3" json:"input_tokens,omitempty"`
	OutputTokens  int32                  `protobuf:"varint,4,opt,name=output_tokens,json=outputTokens,proto3" json:"output_tokens,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TokenUsageEvent) Reset() {
	*x = TokenUsageEvent{}
	mi := &file_core_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TokenUsageEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenUsageEvent) ProtoMessage() {}

func (x *TokenUsageEvent) ProtoReflect() protoreflect.Message {
	mi := &file_core_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenUsageEvent.ProtoReflect.Descriptor instead.
func (*TokenUsageEvent) Descriptor() ([]byte, []int) {
	return file_core_agent_proto_rawDescGZIP(), []int{4}
}

func (x *TokenUsageEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *TokenUsageEvent) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *TokenUsageEvent) GetInputTokens() int32 {
	if x != nil {
		return x.InputTokens
	}
	return 0
}

func (x *TokenUsageEvent) GetOutputTokens() int32 {
	if x != nil {
		return x.OutputTokens
	}
	return 0
}

type WorkflowStartedEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TraceId            string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ExecutionSessionId string                 `protobuf:"bytes,2,opt,name=execution_session_id,json=executionSessionId,proto3" json:"execution_session_id,omitempty"`
	Orchestration      string                 `protobuf:"bytes,3,opt,name=orchestration,proto3" json:"orchestration,omitempty"`
	Status             string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Summary            string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkflowStartedEvent) Reset() {
	*x = WorkflowStartedEvent{}
	mi := &file_core_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStartedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStartedEvent) ProtoMessage() {}

func (x *WorkflowStartedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_core_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStartedEvent.ProtoReflect.Descriptor instead.
func (*WorkflowStartedEvent) Descriptor() ([]byte, []int) {
	return file_core_agent_proto_rawDescGZIP(), []int{5}
}

func (x *WorkflowStartedEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *WorkflowStartedEvent) GetExecutionSessionId() string {
	if x != nil {
		return x.ExecutionSessionId
	}
	return ""
}

func (x *WorkflowStartedEvent) GetOrchestration() string {
	if x != nil {
		return x.Orchestration
	}
	return ""
}

func (x *WorkflowStartedEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowStartedEvent) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

type ThinkingItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	ContentType   string                 `protobuf:"bytes,2,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Text          string                 `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	ToolName      string                 `protobuf:"bytes,4,opt,name=tool_name,json=toolName,proto3" json:"tool_name,omitempty"`
	Arguments     string                 `protobuf:"bytes,5,opt,name=arguments,proto3" json:"arguments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThinkingItem) Reset() {
	*x = ThinkingItem{}
	mi := &file_core_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThinkingItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThinkingItem) ProtoMessage() {}

func (x *ThinkingItem) ProtoReflect() protoreflect.Message {
	mi := &file_core_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThinkingItem.ProtoReflect.Descriptor instead.
func (*ThinkingItem) Descriptor() ([]byte, []int) {
	return file_core_agent_proto_rawDescGZIP(), []int{6}
}

func (x *ThinkingItem) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ThinkingItem) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *ThinkingItem) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *ThinkingItem) GetToolName() string {
	if x != nil {
		return x.ToolName
	}
	return ""
}

func (x *ThinkingItem) GetArguments() string {
	if x != nil {
		return x.Arguments
	}
	return ""
}

type WorkflowTraceNode struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentId       string                 `protobuf:"bytes,1,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentRole     string                 `protobuf:"bytes,2,opt,name=agent_role,json=agentRole,proto3" json:"agent_role,omitempty"`
	IsLeader      bool                   `protobuf:"varint,3,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	Order         int32                  `protobuf:"varint,4,opt,name=order,proto3" json:"order,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	Preview       string                 `protobuf:"bytes,6,opt,name=preview,proto3" json:"preview,omitempty"`
	Response      string                 `protobuf:"bytes,7,opt,name=response,proto3" json:"response,omitempty"`
	Error         string                 `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
	StartedAt     string                 `protobuf:"bytes,9,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt   string                 `protobuf:"bytes,10,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Thinking      []*ThinkingItem        `protobuf:"bytes,11,rep,name=thinking,proto3" json:"thinking,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkflowTraceNode) Reset() {
	*x = WorkflowTraceNode{}
	mi := &file_core_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowTraceNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowTraceNode) ProtoMessage() {}

func (x *WorkflowTraceNode) ProtoReflect() protoreflect.Message {
	mi := &file_core_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowTraceNode.ProtoReflect.Descriptor instead.
func (*WorkflowTraceNode) Descriptor() ([]byte, []int) {
	return file_core_agent_proto_rawDescGZIP(), []int{7}
}

func (x *WorkflowTraceNode) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *WorkflowTraceNode) GetAgentRole() string {
	if x != nil {
		return x.AgentRole
	}
	return ""
}

func (x *WorkflowTraceNode) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *WorkflowTraceNode) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *WorkflowTraceNode) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowTraceNode) GetPreview() string {
	if x != nil {
		return x.Preview
	}
	return ""
}

func (x *WorkflowTraceNode) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *WorkflowTraceNode) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WorkflowTraceNode) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *WorkflowTraceNode) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *WorkflowTraceNode) GetThinking() []*ThinkingItem {
	if x != nil {
		return x.Thinking
	}
	return nil
}

type WorkflowNodeUpdatedEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TraceId            string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ExecutionSessionId string                 `protobuf:"bytes,2,opt,name=execution_session_id,json=executionSessionId,proto3" json:"execution_session_id,omitempty"`
	Orchestration      string                 `protobuf:"bytes,3,opt,name=orchestration,proto3" json:"orchestration,omitempty"`
	Status             string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Summary            string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	AgentId            string                 `protobuf:"bytes,6,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	AgentRole          string                 `protobuf:"bytes,7,opt,name=agent_role,json=agentRole,proto3" json:"agent_role,omitempty"`
	Order              int32                  `protobuf:"varint,8,opt,name=order,proto3" json:"order,omitempty"`
	Preview            string                 `protobuf:"bytes,9,opt,name=preview,proto3" json:"preview,omitempty"`
	Response           string                 `protobuf:"bytes,10,opt,name=response,proto3" json:"response,omitempty"`
	Error              string                 `protobuf:"bytes,11,opt,name=error,proto3" json:"error,omitempty"`
	StartedAt          string                 `protobuf:"bytes,12,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	CompletedAt        string                 `protobuf:"bytes,13,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	IsLeader           bool                   `protobuf:"varint,14,opt,name=is_leader,json=isLeader,proto3" json:"is_leader,omitempty"`
	Thinking           []*ThinkingItem        `protobuf:"bytes,15,rep,name=thinking,proto3" json:"thinking,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkflowNodeUpdatedEvent) Reset() {
	*x = WorkflowNodeUpdatedEvent{}
	mi := &file_core_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowNodeUpdatedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowNodeUpdatedEvent) ProtoMessage() {}

func (x *WorkflowNodeUpdatedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_core_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowNodeUpdatedEvent.ProtoReflect.Descriptor instead.
func (*WorkflowNodeUpdatedEvent) Descriptor() ([]byte, []int) {
	return file_core_agent_proto_rawDescGZIP(), []int{8}
}

func (x *WorkflowNodeUpdatedEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *WorkflowNodeUpdatedEvent) GetExecutionSessionId() string {
	if x != nil {
		return x.ExecutionSessionId
	}
	return ""
}

func (x *WorkflowNodeUpdatedEvent) GetOrchestration() string {
	if x != nil {
		return x.Orchestration
	}
	return ""
}

func (x *WorkflowNodeUpdatedEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowNodeUpdatedEvent) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *WorkflowNodeUpdatedEvent) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *WorkflowNodeUpdatedEvent) GetAgentRole() string {
	if x != nil {
		return x.AgentRole
	}
	return ""
}

func (x *WorkflowNodeUpdatedEvent) GetOrder() int32 {
	if x != nil {
		return x.Order
	}
	return 0
}

func (x *WorkflowNodeUpdatedEvent) GetPreview() string {
	if x != nil {
		return x.Preview
	}
	return ""
}

func (x *WorkflowNodeUpdatedEvent) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

func (x *WorkflowNodeUpdatedEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WorkflowNodeUpdatedEvent) GetStartedAt() string {
	if x != nil {
		return x.StartedAt
	}
	return ""
}

func (x *WorkflowNodeUpdatedEvent) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *WorkflowNodeUpdatedEvent) GetIsLeader() bool {
	if x != nil {
		return x.IsLeader
	}
	return false
}

func (x *WorkflowNodeUpdatedEvent) GetThinking() []*ThinkingItem {
	if x != nil {
		return x.Thinking
	}
	return nil
}

type WorkflowCompletedEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TraceId            string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ExecutionSessionId string                 `protobuf:"bytes,2,opt,name=execution_session_id,json=executionSessionId,proto3" json:"execution_session_id,omitempty"`
	Orchestration      string                 `protobuf:"bytes,3,opt,name=orchestration,proto3" json:"orchestration,omitempty"`
	Status             string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Summary            string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	CompletedAt        string                 `protobuf:"bytes,6,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Nodes              []*WorkflowTraceNode   `protobuf:"bytes,7,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkflowCompletedEvent) Reset() {
	*x = WorkflowCompletedEvent{}
	mi := &file_core_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowCompletedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowCompletedEvent) ProtoMessage() {}

func (x *WorkflowCompletedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_core_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowCompletedEvent.ProtoReflect.Descriptor instead.
func (*WorkflowCompletedEvent) Descriptor() ([]byte, []int) {
	return file_core_agent_proto_rawDescGZIP(), []int{9}
}

func (x *WorkflowCompletedEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *WorkflowCompletedEvent) GetExecutionSessionId() string {
	if x != nil {
		return x.ExecutionSessionId
	}
	return ""
}

func (x *WorkflowCompletedEvent) GetOrchestration() string {
	if x != nil {
		return x.Orchestration
	}
	return ""
}

func (x *WorkflowCompletedEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowCompletedEvent) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *WorkflowCompletedEvent) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *WorkflowCompletedEvent) GetNodes() []*WorkflowTraceNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type WorkflowFailedEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TraceId            string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ExecutionSessionId string                 `protobuf:"bytes,2,opt,name=execution_session_id,json=executionSessionId,proto3" json:"execution_session_id,omitempty"`
	Orchestration      string                 `protobuf:"bytes,3,opt,name=orchestration,proto3" json:"orchestration,omitempty"`
	Status             string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Summary            string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	Error              string                 `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	CompletedAt        string                 `protobuf:"bytes,7,opt,name=completed_at,json=completedAt,proto3" json:"completed_at,omitempty"`
	Nodes              []*WorkflowTraceNode   `protobuf:"bytes,8,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkflowFailedEvent) Reset() {
	*x = WorkflowFailedEvent{}
	mi := &file_core_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowFailedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowFailedEvent) ProtoMessage() {}

func (x *WorkflowFailedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_core_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowFailedEvent.ProtoReflect.Descriptor instead.
func (*WorkflowFailedEvent) Descriptor() ([]byte, []int) {
	return file_core_agent_proto_rawDescGZIP(), []int{10}
}

func (x *WorkflowFailedEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *WorkflowFailedEvent) GetExecutionSessionId() string {
	if x != nil {
		return x.ExecutionSessionId
	}
	return ""
}

func (x *WorkflowFailedEvent) GetOrchestration() string {
	if x != nil {
		return x.Orchestration
	}
	return ""
}

func (x *WorkflowFailedEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowFailedEvent) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *WorkflowFailedEvent) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *WorkflowFailedEvent) GetCompletedAt() string {
	if x != nil {
		return x.CompletedAt
	}
	return ""
}

func (x *WorkflowFailedEvent) GetNodes() []*WorkflowTraceNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type WorkflowStoppedEvent struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TraceId            string                 `protobuf:"bytes,1,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	ExecutionSessionId string                 `protobuf:"bytes,2,opt,name=execution_session_id,json=executionSessionId,proto3" json:"execution_session_id,omitempty"`
	Orchestration      string                 `protobuf:"bytes,3,opt,name=orchestration,proto3" json:"orchestration,omitempty"`
	Status             string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	Summary            string                 `protobuf:"bytes,5,opt,name=summary,proto3" json:"summary,omitempty"`
	StoppedAt          string                 `protobuf:"bytes,6,opt,name=stopped_at,json=stoppedAt,proto3" json:"stopped_at,omitempty"`
	RunId              string                 `protobuf:"bytes,7,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Nodes              []*WorkflowTraceNode   `protobuf:"bytes,8,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WorkflowStoppedEvent) Reset() {
	*x = WorkflowStoppedEvent{}
	mi := &file_core_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowStoppedEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowStoppedEvent) ProtoMessage() {}

func (x *WorkflowStoppedEvent) ProtoReflect() protoreflect.Message {
	mi := &file_core_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowStoppedEvent.ProtoReflect.Descriptor instead.
func (*WorkflowStoppedEvent) Descriptor() ([]byte, []int) {
	return file_core_agent_proto_rawDescGZIP(), []int{11}
}

func (x *WorkflowStoppedEvent) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *WorkflowStoppedEvent) GetExecutionSessionId() string {
	if x != nil {
		return x.ExecutionSessionId
	}
	return ""
}

func (x *WorkflowStoppedEvent) GetOrchestration() string {
	if x != nil {
		return x.Orchestration
	}
	return ""
}

func (x *WorkflowStoppedEvent) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *WorkflowStoppedEvent) GetSummary() string {
	if x != nil {
		return x.Summary
	}
	return ""
}

func (x *WorkflowStoppedEvent) GetStoppedAt() string {
	if x != nil {
		return x.StoppedAt
	}
	return ""
}

func (x *WorkflowStoppedEvent) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *WorkflowStoppedEvent) GetNodes() []*WorkflowTraceNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type WorkflowPresentationPromptEvent struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	PromptId        string                 `protobuf:"bytes,1,opt,name=prompt_id,json=promptId,proto3" json:"prompt_id,omitempty"`
	Question        string                 `protobuf:"bytes,2,opt,name=question,proto3" json:"question,omitempty"`
	OriginalMessage string                 `protobuf:"bytes,3,opt,name=original_message,json=originalMessage,proto3" json:"original_message,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WorkflowPresentationPromptEvent) Reset() {
	*x = WorkflowPresentationPromptEvent{}
	mi := &file_core_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkflowPresentationPromptEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkflowPresentationPromptEvent) ProtoMessage() {}

func (x *WorkflowPresentationPromptEvent) ProtoReflect() protoreflect.Message {
	mi := &file_core_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkflowPresentationPromptEvent.ProtoReflect.Descriptor instead.
func (*WorkflowPresentationPromptEvent) Descriptor() ([]byte, []int) {
	return file_core_agent_proto_rawDescGZIP(), []int{12}
}

func (x *WorkflowPresentationPromptEvent) GetPromptId() string {
	if x != nil {
		return x.PromptId
	}
	return ""
}

func (x *WorkflowPresentationPromptEvent) GetQuestion() string {
	if x != nil {
		return x.Question
	}
	return ""
}

func (x *WorkflowPresentationPromptEvent) GetOriginalMessage() string {
	if x != nil {
		return x.OriginalMessage
	}
	return ""
}

type ChatResponse struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	SessionId string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AgentId   string                 `protobuf:"bytes,2,opt,name=agent_id,json=agentId,proto3" json:"agent_id,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ChatResponse_Reply
	//	*ChatResponse_PlanCreated
	//	*ChatResponse_Error
	//	*ChatResponse_SessionRenamed
	//	*ChatResponse_TokenUsage
	//	*ChatResponse_WorkflowStarted
	//	*ChatResponse_WorkflowNodeUpdated
	//	*ChatResponse_WorkflowCompleted
	//	*ChatResponse_WorkflowFailed
	//	*ChatResponse_WorkflowPresentationPrompt
	//	*ChatResponse_WorkflowStopped
	Payload       isChatResponse_Payload `protobuf_oneof:"payload"`
	RunId         string                 `protobuf:"bytes,14,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"` // Execution run identity for streamed execution events
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatResponse) Reset() {
	*x = ChatResponse{}
	mi := &file_core_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatResponse) ProtoMessage() {}

func (x *ChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatResponse.ProtoReflect.Descriptor instead.
func (*ChatResponse) Descriptor() ([]byte, []int) {
	return file_core_agent_proto_rawDescGZIP(), []int{13}
}

func (x *ChatResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ChatResponse) GetAgentId() string {
	if x != nil {
		return x.AgentId
	}
	return ""
}

func (x *ChatResponse) GetPayload() isChatResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ChatResponse) GetReply() string {
	if x != nil {
		if x, ok := x.Payload.(*ChatResponse_Reply); ok {
			return x.Reply
		}
	}
	return ""
}

func (x *ChatResponse) GetPlanCreated() *PlanCreatedEvent {
	if x != nil {
		if x, ok := x.Payload.(*ChatResponse_PlanCreated); ok {
			return x.PlanCreated
		}
	}
	return nil
}

func (x *ChatResponse) GetError() string {
	if x != nil {
		if x, ok := x.Payload.(*ChatResponse_Error); ok {
			return x.Error
		}
	}
	return ""
}

func (x *ChatResponse) GetSessionRenamed() *SessionRenamedEvent {
	if x != nil {
		if x, ok := x.Payload.(*ChatResponse_SessionRenamed); ok {
			return x.SessionRenamed
		}
	}
	return nil
}

func (x *ChatResponse) GetTokenUsage() *TokenUsageEvent {
	if x != nil {
		if x, ok := x.Payload.(*ChatResponse_TokenUsage); ok {
			return x.TokenUsage
		}
	}
	return nil
}

func (x *ChatResponse) GetWorkflowStarted() *WorkflowStartedEvent {
	if x != nil {
		if x, ok := x.Payload.(*ChatResponse_WorkflowStarted); ok {
			return x.WorkflowStarted
		}
	}
	return nil
}

func (x *ChatResponse) GetWorkflowNodeUpdated() *WorkflowNodeUpdatedEvent {
	if x != nil {
		if x, ok := x.Payload.(*ChatResponse_WorkflowNodeUpdated); ok {
			return x.WorkflowNodeUpdated
		}
	}
	return nil
}

func (x *ChatResponse) GetWorkflowCompleted() *WorkflowCompletedEvent {
	if x != nil {
		if x, ok := x.Payload.(*ChatResponse_WorkflowCompleted); ok {
			return x.WorkflowCompleted
		}
	}
	return nil
}

func (x *ChatResponse) GetWorkflowFailed() *WorkflowFailedEvent {
	if x != nil {
		if x, ok := x.Payload.(*ChatResponse_WorkflowFailed); ok {
			return x.WorkflowFailed
		}
	}
	return nil
}

func (x *ChatResponse) GetWorkflowPresentationPrompt() *WorkflowPresentationPromptEvent {
	if x != nil {
		if x, ok := x.Payload.(*ChatResponse_WorkflowPresentationPrompt); ok {
			return x.WorkflowPresentationPrompt
		}
	}
	return nil
}

func (x *ChatResponse) GetWorkflowStopped() *WorkflowStoppedEvent {
	if x != nil {
		if x, ok := x.Payload.(*ChatResponse_WorkflowStopped); ok {
			return x.WorkflowStopped
		}
	}
	return nil
}

func (x *ChatResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type isChatResponse_Payload interface {
	isChatResponse_Payload()
}

type ChatResponse_Reply struct {
	Reply string `protobuf:"bytes,3,opt,name=reply,proto3,oneof"` // Text chunk (existing)
}

type ChatResponse_PlanCreated struct {
	PlanCreated *PlanCreatedEvent `protobuf:"bytes,4,opt,name=plan_created,json=planCreated,proto3,oneof"` // Structured plan event
}

type ChatResponse_Error struct {
	Error string `protobuf:"bytes,5,opt,name=error,proto3,oneof"` // Error message
}

type ChatResponse_SessionRenamed struct {
	SessionRenamed *SessionRenamedEvent `protobuf:"bytes,6,opt,name=session_renamed,json=sessionRenamed,proto3,oneof"` // Session title rename event
}

type ChatResponse_TokenUsage struct {
	TokenUsage *TokenUsageEvent `protobuf:"bytes,7,opt,name=token_usage,json=tokenUsage,proto3,oneof"` // Token consumption event
}

type ChatResponse_WorkflowStarted struct {
	WorkflowStarted *WorkflowStartedEvent `protobuf:"bytes,8,opt,name=workflow_started,json=workflowStarted,proto3,oneof"`
}

type ChatResponse_WorkflowNodeUpdated struct {
	WorkflowNodeUpdated *WorkflowNodeUpdatedEvent `protobuf:"bytes,9,opt,name=workflow_node_updated,json=workflowNodeUpdated,proto3,oneof"`
}

type ChatResponse_WorkflowCompleted struct {
	WorkflowCompleted *WorkflowCompletedEvent `protobuf:"bytes,10,opt,name=workflow_completed,json=workflowCompleted,proto3,oneof"`
}

type ChatResponse_WorkflowFailed struct {
	WorkflowFailed *WorkflowFailedEvent `protobuf:"bytes,11,opt,name=workflow_failed,json=workflowFailed,proto3,oneof"`
}

type ChatResponse_WorkflowPresentationPrompt struct {
	WorkflowPresentationPrompt *WorkflowPresentationPromptEvent `protobuf:"bytes,12,opt,name=workflow_presentation_prompt,json=workflowPresentationPrompt,proto3,oneof"`
}

type ChatResponse_WorkflowStopped struct {
	WorkflowStopped *WorkflowStoppedEvent `protobuf:"bytes,13,opt,name=workflow_stopped,json=workflowStopped,proto3,oneof"`
}

func (*ChatResponse_Reply) isChatResponse_Payload() {}

func (*ChatResponse_PlanCreated) isChatResponse_Payload() {}

func (*ChatResponse_Error) isChatResponse_Payload() {}

func (*ChatResponse_SessionRenamed) isChatResponse_Payload() {}

func (*ChatResponse_TokenUsage) isChatResponse_Payload() {}

func (*ChatResponse_WorkflowStarted) isChatResponse_Payload() {}

func (*ChatResponse_WorkflowNodeUpdated) isChatResponse_Payload() {}

func (*ChatResponse_WorkflowCompleted) isChatResponse_Payload() {}

func (*ChatResponse_WorkflowFailed) isChatResponse_Payload() {}

func (*ChatResponse_WorkflowPresentationPrompt) isChatResponse_Payload() {}

func (*ChatResponse_WorkflowStopped) isChatResponse_Payload() {}

type AgentListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Role          string                 `protobuf:"bytes,1,opt,name=role,proto3" json:"role,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentListResponse) Reset() {
	*x = AgentListResponse{}
	mi := &file_core_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentListResponse) ProtoMessage() {}

func (x *AgentListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentListResponse.ProtoReflect.Descriptor instead.
func (*AgentListResponse) Descriptor() ([]byte, []int) {
	return file_core_agent_proto_rawDescGZIP(), []int{14}
}

func (x *AgentListResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *AgentListResponse) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ExecutePlanRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutePlanRequest) Reset() {
	*x = ExecutePlanRequest{}
	mi := &file_core_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePlanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePlanRequest) ProtoMessage() {}

func (x *ExecutePlanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePlanRequest.ProtoReflect.Descriptor instead.
func (*ExecutePlanRequest) Descriptor() ([]byte, []int) {
	return file_core_agent_proto_rawDescGZIP(), []int{15}
}

func (x *ExecutePlanRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

type ExecutePlanResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Result        string                 `protobuf:"bytes,2,opt,name=result,proto3" json:"result,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutePlanResponse) Reset() {
	*x = ExecutePlanResponse{}
	mi := &file_core_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutePlanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutePlanResponse) ProtoMessage() {}

func (x *ExecutePlanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutePlanResponse.ProtoReflect.Descriptor instead.
func (*ExecutePlanResponse) Descriptor() ([]byte, []int) {
	return file_core_agent_proto_rawDescGZIP(), []int{16}
}

func (x *ExecutePlanResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *ExecutePlanResponse) GetResult() string {
	if x != nil {
		return x.Result
	}
	return ""
}

func (x *ExecutePlanResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// StopRun targets the active execution run within an execution session.
// The call is acknowledgement-oriented and may be handled idempotently by the server.
type StopRunRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ExecutionSessionId string                 `protobuf:"bytes,1,opt,name=execution_session_id,json=executionSessionId,proto3" json:"execution_session_id,omitempty"`
	RunId              string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StopRunRequest) Reset() {
	*x = StopRunRequest{}
	mi := &file_core_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRunRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRunRequest) ProtoMessage() {}

func (x *StopRunRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRunRequest.ProtoReflect.Descriptor instead.
func (*StopRunRequest) Descriptor() ([]byte, []int) {
	return file_core_agent_proto_rawDescGZIP(), []int{17}
}

func (x *StopRunRequest) GetExecutionSessionId() string {
	if x != nil {
		return x.ExecutionSessionId
	}
	return ""
}

func (x *StopRunRequest) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

type StopRunResponse struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ExecutionSessionId string                 `protobuf:"bytes,1,opt,name=execution_session_id,json=executionSessionId,proto3" json:"execution_session_id,omitempty"`
	RunId              string                 `protobuf:"bytes,2,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	Status             string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Message            string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *StopRunResponse) Reset() {
	*x = StopRunResponse{}
	mi := &file_core_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopRunResponse) ProtoMessage() {}

func (x *StopRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopRunResponse.ProtoReflect.Descriptor instead.
func (*StopRunResponse) Descriptor() ([]byte, []int) {
	return file_core_agent_proto_rawDescGZIP(), []int{18}
}

func (x *StopRunResponse) GetExecutionSessionId() string {
	if x != nil {
		return x.ExecutionSessionId
	}
	return ""
}

func (x *StopRunResponse) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

func (x *StopRunResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *StopRunResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DocumentContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FileKey       string                 `protobuf:"bytes,1,opt,name=file_key,json=fileKey,proto3" json:"file_key,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	FileName      string                 `protobuf:"bytes,3,opt,name=file_name,json=fileName,proto3" json:"file_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DocumentContent) Reset() {
	*x = DocumentContent{}
	mi := &file_core_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DocumentContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DocumentContent) ProtoMessage() {}

func (x *DocumentContent) ProtoReflect() protoreflect.Message {
	mi := &file_core_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DocumentContent.ProtoReflect.Descriptor instead.
func (*DocumentContent) Descriptor() ([]byte, []int) {
	return file_core_agent_proto_rawDescGZIP(), []int{19}
}

func (x *DocumentContent) GetFileKey() string {
	if x != nil {
		return x.FileKey
	}
	return ""
}

func (x *DocumentContent) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *DocumentContent) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

type EvaluateRAGRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ReferenceId        string                 `protobuf:"bytes,1,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	UserId             string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Documents          []*DocumentContent     `protobuf:"bytes,3,rep,name=documents,proto3" json:"documents,omitempty"`
	SessionName        string                 `protobuf:"bytes,4,opt,name=session_name,json=sessionName,proto3" json:"session_name,omitempty"`
	SessionDescription string                 `protobuf:"bytes,5,opt,name=session_description,json=sessionDescription,proto3" json:"session_description,omitempty"`
	AgentRoles         []string               `protobuf:"bytes,6,rep,name=agent_roles,json=agentRoles,proto3" json:"agent_roles,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EvaluateRAGRequest) Reset() {
	*x = EvaluateRAGRequest{}
	mi := &file_core_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRAGRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRAGRequest) ProtoMessage() {}

func (x *EvaluateRAGRequest) ProtoReflect() protoreflect.Message {
	mi := &file_core_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRAGRequest.ProtoReflect.Descriptor instead.
func (*EvaluateRAGRequest) Descriptor() ([]byte, []int) {
	return file_core_agent_proto_rawDescGZIP(), []int{20}
}

func (x *EvaluateRAGRequest) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *EvaluateRAGRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *EvaluateRAGRequest) GetDocuments() []*DocumentContent {
	if x != nil {
		return x.Documents
	}
	return nil
}

func (x *EvaluateRAGRequest) GetSessionName() string {
	if x != nil {
		return x.SessionName
	}
	return ""
}

func (x *EvaluateRAGRequest) GetSessionDescription() string {
	if x != nil {
		return x.SessionDescription
	}
	return ""
}

func (x *EvaluateRAGRequest) GetAgentRoles() []string {
	if x != nil {
		return x.AgentRoles
	}
	return nil
}

type RAGMetricResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MetricName    string                 `protobuf:"bytes,1,opt,name=metric_name,json=metricName,proto3" json:"metric_name,omitempty"`
	Score         float64                `protobuf:"fixed64,2,opt,name=score,proto3" json:"score,omitempty"`
	Passed        bool                   `protobuf:"varint,3,opt,name=passed,proto3" json:"passed,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RAGMetricResult) Reset() {
	*x = RAGMetricResult{}
	mi := &file_core_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RAGMetricResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RAGMetricResult) ProtoMessage() {}

func (x *RAGMetricResult) ProtoReflect() protoreflect.Message {
	mi := &file_core_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RAGMetricResult.ProtoReflect.Descriptor instead.
func (*RAGMetricResult) Descriptor() ([]byte, []int) {
	return file_core_agent_proto_rawDescGZIP(), []int{21}
}

func (x *RAGMetricResult) GetMetricName() string {
	if x != nil {
		return x.MetricName
	}
	return ""
}

func (x *RAGMetricResult) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

func (x *RAGMetricResult) GetPassed() bool {
	if x != nil {
		return x.Passed
	}
	return false
}

func (x *RAGMetricResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type EvaluateRAGResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReferenceId    string                 `protobuf:"bytes,1,opt,name=reference_id,json=referenceId,proto3" json:"reference_id,omitempty"`
	OverallScore   float64                `protobuf:"fixed64,2,opt,name=overall_score,json=overallScore,proto3" json:"overall_score,omitempty"`
	Metrics        []*RAGMetricResult     `protobuf:"bytes,3,rep,name=metrics,proto3" json:"metrics,omitempty"`
	Status         string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	ErrorMessage   string                 `protobuf:"bytes,5,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	TestCasesCount int32                  `protobuf:"varint,6,opt,name=test_cases_count,json=testCasesCount,proto3" json:"test_cases_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EvaluateRAGResponse) Reset() {
	*x = EvaluateRAGResponse{}
	mi := &file_core_agent_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluateRAGResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluateRAGResponse) ProtoMessage() {}

func (x *EvaluateRAGResponse) ProtoReflect() protoreflect.Message {
	mi := &file_core_agent_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluateRAGResponse.ProtoReflect.Descriptor instead.
func (*EvaluateRAGResponse) Descriptor() ([]byte, []int) {
	return file_core_agent_proto_rawDescGZIP(), []int{22}
}

func (x *EvaluateRAGResponse) GetReferenceId() string {
	if x != nil {
		return x.ReferenceId
	}
	return ""
}

func (x *EvaluateRAGResponse) GetOverallScore() float64 {
	if x != nil {
		return x.OverallScore
	}
	return 0
}

func (x *EvaluateRAGResponse) GetMetrics() []*RAGMetricResult {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *EvaluateRAGResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *EvaluateRAGResponse) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *EvaluateRAGResponse) GetTestCasesCount() int32 {
	if x != nil {
		return x.TestCasesCount
	}
	return 0
}

var File_core_agent_proto protoreflect.FileDescriptor

const file_core_agent_proto_rawDesc = "" +
	"\n" +
	"\x10core_agent.proto\x12\n" +
	"core_agent\"\x9b\x01\n" +
	"\vChatRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12&\n" +
	"\x0ftarget_agent_id\x18\x02 \x01(\tR\rtargetAgentId\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12+\n" +
	"\x11presentation_mode\x18\x04 \x01(\tR\x10presentationMode\"\xa2\x01\n" +
	"\tAgentInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\x12\x12\n" +
	"\x04goal\x18\x03 \x01(\tR\x04goal\x12\x14\n" +
	"\x05tools\x18\x04 \x03(\tR\x05tools\x12\x14\n" +
	"\x05model\x18\x05 \x01(\tR\x05model\x12\x14\n" +
	"\x05order\x18\x06 \x01(\x05R\x05order\x12\x1b\n" +
	"\tis_leader\x18\a \x01(\bR\bisLeader\"\x80\x01\n" +
	"\x10PlanCreatedEvent\x12\x17\n" +
	"\aplan_id\x18\x01 \x01(\tR\x06planId\x12$\n" +
	"\rorchestration\x18\x02 \x01(\tR\rorchestration\x12-\n" +
	"\x06agents\x18\x03 \x03(\v2\x15.core_agent.AgentInfoR\x06agents\"J\n" +
	"\x13SessionRenamedEvent\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\"\x8f\x01\n" +
	"\x0fTokenUsageEvent\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12!\n" +
	"\finput_tokens\x18\x03 \x01(\x05R\vinputTokens\x12#\n" +
	"\routput_tokens\x18\x04 \x01(\x05R\foutputTokens\"\xbb\x01\n" +
	"\x14WorkflowStartedEvent\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x120\n" +
	"\x14execution_session_id\x18\x02 \x01(\tR\x12executionSessionId\x12$\n" +
	"\rorchestration\x18\x03 \x01(\tR\rorchestration\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\"\x94\x01\n" +
	"\fThinkingItem\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12!\n" +
	"\fcontent_type\x18\x02 \x01(\tR\vcontentType\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1b\n" +
	"\ttool_name\x18\x04 \x01(\tR\btoolName\x12\x1c\n" +
	"\targuments\x18\x05 \x01(\tR\targuments\"\xdc\x02\n" +
	"\x11WorkflowTraceNode\x12\x19\n" +
	"\bagent_id\x18\x01 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_role\x18\x02 \x01(\tR\tagentRole\x12\x1b\n" +
	"\tis_leader\x18\x03 \x01(\bR\bisLeader\x12\x14\n" +
	"\x05order\x18\x04 \x01(\x05R\x05order\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x18\n" +
	"\apreview\x18\x06 \x01(\tR\apreview\x12\x1a\n" +
	"\bresponse\x18\a \x01(\tR\bresponse\x12\x14\n" +
	"\x05error\x18\b \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"started_at\x18\t \x01(\tR\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\n" +
	" \x01(\tR\vcompletedAt\x124\n" +
	"\bthinking\x18\v \x03(\v2\x18.core_agent.ThinkingItemR\bthinking\"\xf0\x03\n" +
	"\x18WorkflowNodeUpdatedEvent\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x120\n" +
	"\x14execution_session_id\x18\x02 \x01(\tR\x12executionSessionId\x12$\n" +
	"\rorchestration\x18\x03 \x01(\tR\rorchestration\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x19\n" +
	"\bagent_id\x18\x06 \x01(\tR\aagentId\x12\x1d\n" +
	"\n" +
	"agent_role\x18\a \x01(\tR\tagentRole\x12\x14\n" +
	"\x05order\x18\b \x01(\x05R\x05order\x12\x18\n" +
	"\apreview\x18\t \x01(\tR\apreview\x12\x1a\n" +
	"\bresponse\x18\n" +
	" \x01(\tR\bresponse\x12\x14\n" +
	"\x05error\x18\v \x01(\tR\x05error\x12\x1d\n" +
	"\n" +
	"started_at\x18\f \x01(\tR\tstartedAt\x12!\n" +
	"\fcompleted_at\x18\r \x01(\tR\vcompletedAt\x12\x1b\n" +
	"\tis_leader\x18\x0e \x01(\bR\bisLeader\x124\n" +
	"\bthinking\x18\x0f \x03(\v2\x18.core_agent.ThinkingItemR\bthinking\"\x95\x02\n" +
	"\x16WorkflowCompletedEvent\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x120\n" +
	"\x14execution_session_id\x18\x02 \x01(\tR\x12executionSessionId\x12$\n" +
	"\rorchestration\x18\x03 \x01(\tR\rorchestration\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12!\n" +
	"\fcompleted_at\x18\x06 \x01(\tR\vcompletedAt\x123\n" +
	"\x05nodes\x18\a \x03(\v2\x1d.core_agent.WorkflowTraceNodeR\x05nodes\"\xa8\x02\n" +
	"\x13WorkflowFailedEvent\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x120\n" +
	"\x14execution_session_id\x18\x02 \x01(\tR\x12executionSessionId\x12$\n" +
	"\rorchestration\x18\x03 \x01(\tR\rorchestration\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x14\n" +
	"\x05error\x18\x06 \x01(\tR\x05error\x12!\n" +
	"\fcompleted_at\x18\a \x01(\tR\vcompletedAt\x123\n" +
	"\x05nodes\x18\b \x03(\v2\x1d.core_agent.WorkflowTraceNodeR\x05nodes\"\xa6\x02\n" +
	"\x14WorkflowStoppedEvent\x12\x19\n" +
	"\btrace_id\x18\x01 \x01(\tR\atraceId\x120\n" +
	"\x14execution_session_id\x18\x02 \x01(\tR\x12executionSessionId\x12$\n" +
	"\rorchestration\x18\x03 \x01(\tR\rorchestration\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12\x18\n" +
	"\asummary\x18\x05 \x01(\tR\asummary\x12\x1d\n" +
	"\n" +
	"stopped_at\x18\x06 \x01(\tR\tstoppedAt\x12\x15\n" +
	"\x06run_id\x18\a \x01(\tR\x05runId\x123\n" +
	"\x05nodes\x18\b \x03(\v2\x1d.core_agent.WorkflowTraceNodeR\x05nodes\"\x85\x01\n" +
	"\x1fWorkflowPresentationPromptEvent\x12\x1b\n" +
	"\tprompt_id\x18\x01 \x01(\tR\bpromptId\x12\x1a\n" +
	"\bquestion\x18\x02 \x01(\tR\bquestion\x12)\n" +
	"\x10original_message\x18\x03 \x01(\tR\x0foriginalMessage\"\xf5\x06\n" +
	"\fChatResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x19\n" +
	"\bagent_id\x18\x02 \x01(\tR\aagentId\x12\x16\n" +
	"\x05reply\x18\x03 \x01(\tH\x00R\x05reply\x12A\n" +
	"\fplan_created\x18\x04 \x01(\v2\x1c.core_agent.PlanCreatedEventH\x00R\vplanCreated\x12\x16\n" +
	"\x05error\x18\x05 \x01(\tH\x00R\x05error\x12J\n" +
	"\x0fsession_renamed\x18\x06 \x01(\v2\x1f.core_agent.SessionRenamedEventH\x00R\x0esessionRenamed\x12>\n" +
	"\vtoken_usage\x18\a \x01(\v2\x1b.core_agent.TokenUsageEventH\x00R\n" +
	"tokenUsage\x12M\n" +
	"\x10workflow_started\x18\b \x01(\v2 .core_agent.WorkflowStartedEventH\x00R\x0fworkflowStarted\x12Z\n" +
	"\x15workflow_node_updated\x18\t \x01(\v2$.core_agent.WorkflowNodeUpdatedEventH\x00R\x13workflowNodeUpdated\x12S\n" +
	"\x12workflow_completed\x18\n" +
	" \x01(\v2\".core_agent.WorkflowCompletedEventH\x00R\x11workflowCompleted\x12J\n" +
	"\x0fworkflow_failed\x18\v \x01(\v2\x1f.core_agent.WorkflowFailedEventH\x00R\x0eworkflowFailed\x12o\n" +
	"\x1cworkflow_presentation_prompt\x18\f \x01(\v2+.core_agent.WorkflowPresentationPromptEventH\x00R\x1aworkflowPresentationPrompt\x12M\n" +
	"\x10workflow_stopped\x18\r \x01(\v2 .core_agent.WorkflowStoppedEventH\x00R\x0fworkflowStopped\x12\x15\n" +
	"\x06run_id\x18\x0e \x01(\tR\x05runIdB\t\n" +
	"\apayload\"I\n" +
	"\x11AgentListResponse\x12\x12\n" +
	"\x04role\x18\x01 \x01(\tR\x04role\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\"3\n" +
	"\x12ExecutePlanRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"d\n" +
	"\x13ExecutePlanResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x16\n" +
	"\x06result\x18\x02 \x01(\tR\x06result\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\"Y\n" +
	"\x0eStopRunRequest\x120\n" +
	"\x14execution_session_id\x18\x01 \x01(\tR\x12executionSessionId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\"\x8c\x01\n" +
	"\x0fStopRunResponse\x120\n" +
	"\x14execution_session_id\x18\x01 \x01(\tR\x12executionSessionId\x12\x15\n" +
	"\x06run_id\x18\x02 \x01(\tR\x05runId\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"c\n" +
	"\x0fDocumentContent\x12\x19\n" +
	"\bfile_key\x18\x01 \x01(\tR\afileKey\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x1b\n" +
	"\tfile_name\x18\x03 \x01(\tR\bfileName\"\x80\x02\n" +
	"\x12EvaluateRAGRequest\x12!\n" +
	"\freference_id\x18\x01 \x01(\tR\vreferenceId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x129\n" +
	"\tdocuments\x18\x03 \x03(\v2\x1b.core_agent.DocumentContentR\tdocuments\x12!\n" +
	"\fsession_name\x18\x04 \x01(\tR\vsessionName\x12/\n" +
	"\x13session_description\x18\x05 \x01(\tR\x12sessionDescription\x12\x1f\n" +
	"\vagent_roles\x18\x06 \x03(\tR\n" +
	"agentRoles\"x\n" +
	"\x0fRAGMetricResult\x12\x1f\n" +
	"\vmetric_name\x18\x01 \x01(\tR\n" +
	"metricName\x12\x14\n" +
	"\x05score\x18\x02 \x01(\x01R\x05score\x12\x16\n" +
	"\x06passed\x18\x03 \x01(\bR\x06passed\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\xfb\x01\n" +
	"\x13EvaluateRAGResponse\x12!\n" +
	"\freference_id\x18\x01 \x01(\tR\vreferenceId\x12#\n" +
	"\roverall_score\x18\x02 \x01(\x01R\foverallScore\x125\n" +
	"\ametrics\x18\x03 \x03(\v2\x1b.core_agent.RAGMetricResultR\ametrics\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x12#\n" +
	"\rerror_message\x18\x05 \x01(\tR\ferrorMessage\x12(\n" +
	"\x10test_cases_count\x18\x06 \x01(\x05R\x0etestCasesCount2\xf6\x02\n" +
	"\tCoreAgent\x12;\n" +
	"\x04Chat\x12\x17.core_agent.ChatRequest\x1a\x18.core_agent.ChatResponse0\x01\x12H\n" +
	"\fGetAgentList\x12\x17.core_agent.ChatRequest\x1a\x1d.core_agent.AgentListResponse0\x01\x12N\n" +
	"\vExecutePlan\x12\x1e.core_agent.ExecutePlanRequest\x1a\x1f.core_agent.ExecutePlanResponse\x12B\n" +
	"\aStopRun\x12\x1a.core_agent.StopRunRequest\x1a\x1b.core_agent.StopRunResponse\x12N\n" +
	"\vEvaluateRAG\x12\x1e.core_agent.EvaluateRAGRequest\x1a\x1f.core_agent.EvaluateRAGResponseB\x15Z\x13capstone-prog/protob\x06proto3"

var (
	file_core_agent_proto_rawDescOnce sync.Once
	file_core_agent_proto_rawDescData []byte
)

func file_core_agent_proto_rawDescGZIP() []byte {
	file_core_agent_proto_rawDescOnce.Do(func() {
		file_core_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_core_agent_proto_rawDesc), len(file_core_agent_proto_rawDesc)))
	})
	return file_core_agent_proto_rawDescData
}

var file_core_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_core_agent_proto_goTypes = []any{
	(*ChatRequest)(nil),                     // 0: core_agent.ChatRequest
	(*AgentInfo)(nil),                       // 1: core_agent.AgentInfo
	(*PlanCreatedEvent)(nil),                // 2: core_agent.PlanCreatedEvent
	(*SessionRenamedEvent)(nil),             // 3: core_agent.SessionRenamedEvent
	(*TokenUsageEvent)(nil),                 // 4: core_agent.TokenUsageEvent
	(*WorkflowStartedEvent)(nil),            // 5: core_agent.WorkflowStartedEvent
	(*ThinkingItem)(nil),                    // 6: core_agent.ThinkingItem
	(*WorkflowTraceNode)(nil),               // 7: core_agent.WorkflowTraceNode
	(*WorkflowNodeUpdatedEvent)(nil),        // 8: core_agent.WorkflowNodeUpdatedEvent
	(*WorkflowCompletedEvent)(nil),          // 9: core_agent.WorkflowCompletedEvent
	(*WorkflowFailedEvent)(nil),             // 10: core_agent.WorkflowFailedEvent
	(*WorkflowStoppedEvent)(nil),            // 11: core_agent.WorkflowStoppedEvent
	(*WorkflowPresentationPromptEvent)(nil), // 12: core_agent.WorkflowPresentationPromptEvent
	(*ChatResponse)(nil),                    // 13: core_agent.ChatResponse
	(*AgentListResponse)(nil),               // 14: core_agent.AgentListResponse
	(*ExecutePlanRequest)(nil),              // 15: core_agent.ExecutePlanRequest
	(*ExecutePlanResponse)(nil),             // 16: core_agent.ExecutePlanResponse
	(*StopRunRequest)(nil),                  // 17: core_agent.StopRunRequest
	(*StopRunResponse)(nil),                 // 18: core_agent.StopRunResponse
	(*DocumentContent)(nil),                 // 19: core_agent.DocumentContent
	(*EvaluateRAGRequest)(nil),              // 20: core_agent.EvaluateRAGRequest
	(*RAGMetricResult)(nil),                 // 21: core_agent.RAGMetricResult
	(*EvaluateRAGResponse)(nil),             // 22: core_agent.EvaluateRAGResponse
}
var file_core_agent_proto_depIdxs = []int32{
	1,  // 0: core_agent.PlanCreatedEvent.agents:type_name -> core_agent.AgentInfo
	6,  // 1: core_agent.WorkflowTraceNode.thinking:type_name -> core_agent.ThinkingItem
	6,  // 2: core_agent.WorkflowNodeUpdatedEvent.thinking:type_name -> core_agent.ThinkingItem
	7,  // 3: core_agent.WorkflowCompletedEvent.nodes:type_name -> core_agent.WorkflowTraceNode
	7,  // 4: core_agent.WorkflowFailedEvent.nodes:type_name -> core_agent.WorkflowTraceNode
	7,  // 5: core_agent.WorkflowStoppedEvent.nodes:type_name -> core_agent.WorkflowTraceNode
	2,  // 6: core_agent.ChatResponse.plan_created:type_name -> core_agent.PlanCreatedEvent
	3,  // 7: core_agent.ChatResponse.session_renamed:type_name -> core_agent.SessionRenamedEvent
	4,  // 8: core_agent.ChatResponse.token_usage:type_name -> core_agent.TokenUsageEvent
	5,  // 9: core_agent.ChatResponse.workflow_started:type_name -> core_agent.WorkflowStartedEvent
	8,  // 10: core_agent.ChatResponse.workflow_node_updated:type_name -> core_agent.WorkflowNodeUpdatedEvent
	9,  // 11: core_agent.ChatResponse.workflow_completed:type_name -> core_agent.WorkflowCompletedEvent
	10, // 12: core_agent.ChatResponse.workflow_failed:type_name -> core_agent.WorkflowFailedEvent
	12, // 13: core_agent.ChatResponse.workflow_presentation_prompt:type_name -> core_agent.WorkflowPresentationPromptEvent
	11, // 14: core_agent.ChatResponse.workflow_stopped:type_name -> core_agent.WorkflowStoppedEvent
	19, // 15: core_agent.EvaluateRAGRequest.documents:type_name -> core_agent.DocumentContent
	21, // 16: core_agent.EvaluateRAGResponse.metrics:type_name -> core_agent.RAGMetricResult
	0,  // 17: core_agent.CoreAgent.Chat:input_type -> core_agent.ChatRequest
	0,  // 18: core_agent.CoreAgent.GetAgentList:input_type -> core_agent.ChatRequest
	15, // 19: core_agent.CoreAgent.ExecutePlan:input_type -> core_agent.ExecutePlanRequest
	17, // 20: core_agent.CoreAgent.StopRun:input_type -> core_agent.StopRunRequest
	20, // 21: core_agent.CoreAgent.EvaluateRAG:input_type -> core_agent.EvaluateRAGRequest
	13, // 22: core_agent.CoreAgent.Chat:output_type -> core_agent.ChatResponse
	14, // 23: core_agent.CoreAgent.GetAgentList:output_type -> core_agent.AgentListResponse
	16, // 24: core_agent.CoreAgent.ExecutePlan:output_type -> core_agent.ExecutePlanResponse
	18, // 25: core_agent.CoreAgent.StopRun:output_type -> core_agent.StopRunResponse
	22, // 26: core_agent.CoreAgent.EvaluateRAG:output_type -> core_agent.EvaluateRAGResponse
	22, // [22:27] is the sub-list for method output_type
	17, // [17:22] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_core_agent_proto_init() }
func file_core_agent_proto_init() {
	if File_core_agent_proto != nil {
		return
	}
	file_core_agent_proto_msgTypes[13].OneofWrappers = []any{
		(*ChatResponse_Reply)(nil),
		(*ChatResponse_PlanCreated)(nil),
		(*ChatResponse_Error)(nil),
		(*ChatResponse_SessionRenamed)(nil),
		(*ChatResponse_TokenUsage)(nil),
		(*ChatResponse_WorkflowStarted)(nil),
		(*ChatResponse_WorkflowNodeUpdated)(nil),
		(*ChatResponse_WorkflowCompleted)(nil),
		(*ChatResponse_WorkflowFailed)(nil),
		(*ChatResponse_WorkflowPresentationPrompt)(nil),
		(*ChatResponse_WorkflowStopped)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_core_agent_proto_rawDesc), len(file_core_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_core_agent_proto_goTypes,
		DependencyIndexes: file_core_agent_proto_depIdxs,
		MessageInfos:      file_core_agent_proto_msgTypes,
	}.Build()
	File_core_agent_proto = out.File
	file_core_agent_proto_goTypes = nil
	file_core_agent_proto_depIdxs = nil
}
