from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict

# Always resolves to agent/.env regardless of the working directory.
_ENV_FILE = Path(__file__).parent.parent / ".env"


class Settings(BaseSettings):
    model_config = SettingsConfigDict(
        env_file=_ENV_FILE,
        env_file_encoding="utf-8",
        extra="ignore",
    )

    # ── LLM (OpenRouter) ──────────────────────────────────────────────────────
    GLM_API_KEY: str = ""
    GLM_BASE_URL: str = "https://api.z.ai/api/paas/v4"

    CORE_MODEL: str = "openrouter/hunter-alpha"
    MODEL: str = "openrouter/hunter-alpha"

    GLM_CORE_MODEL: str = "glm-4.5-flash"

    # ── gRPC server ───────────────────────────────────────────────────────────
    GRPC_HOST: str = "localhost"
    GRPC_PORT: int = 50051

    # ── Fallback WebSocket server ─────────────────────────────────────────────
    WS_HOST: str = "0.0.0.0"
    WS_PORT: int = 50052

    # ── Runtime environment ───────────────────────────────────────────────────
    ENVIRONMENT: str = "debug"

    # ── Jina AI (web search & fetch tools) ───────────────────────────────────
    JINA_API_KEY: str = ""

    # ── OpenRouter Embeddings ────────────────────────────────────────────────
    OPENROUTER_EMBED_MODEL: str = "qwen/qwen3-embedding-8b"
    OPENROUTER_EMBED_URL: str = "https://openrouter.ai/api/v1/embeddings"

    # ── Google Workspace (service account) ─────────────────────────────────────
    GOOGLE_SA_PROJECT_ID: str = ""
    GOOGLE_SA_PRIVATE_KEY_ID: str = ""
    GOOGLE_SA_PRIVATE_KEY: str = ""      # RSA key — store \n as literal \n in .env
    GOOGLE_SA_CLIENT_EMAIL: str = ""
    GOOGLE_SA_CLIENT_ID: str = ""
    GOOGLE_SHARE_WITH_EMAIL: str = ""  # transfer ownership of created files to this email
    GOOGLE_DRIVE_FOLDER_ID: str = ""  # move created files into this Drive folder

    # ── OpenRouter (LLM judge for evaluation) ─────────────────────────────────
    OPENROUTER_API_KEY: str = ""
    OPENROUTER_BASE_URL: str = "https://openrouter.ai/api/v1"
    JUDGE_MODEL: str = "openrouter/hunter-alpha"

    # ── Cloudflare R2 (image storage) ─────────────────────────────────────────
    R2_ACCESS_KEY_ID: str = ""
    R2_SECRET_ACCESS_KEY: str = ""
    R2_ENDPOINT: str = ""        # e.g. https://<account-id>.r2.cloudflarestorage.com
    R2_BUCKET: str = ""
    R2_PUBLIC_URL: str = ""      # e.g. https://pub-xxx.r2.dev or custom domain

    # ── Backend API ───────────────────────────────────────────────────────────
    BACKEND_URL: str = "http://localhost:8080"
    # Pre-shared service token used by the agent for internal backend calls.
    # Set this to a long-lived admin JWT generated by the backend.
    BACKEND_SERVICE_TOKEN: str = ""

    # ── PostgreSQL (pgvector) ─────────────────────────────────────────────────
    DB_HOST: str = "localhost"
    DB_PORT: int = 5433  # pgvector container port
    DB_NAME: str = "egco_capstone"
    DB_USER: str = "postgres"
    DB_PASSWORD: str = ""

    # ── Connection pool ───────────────────────────────────────────────────────
    DB_POOL_MIN: int = 2
    DB_POOL_MAX: int = 10

    # ── Redis (embedding cache) ───────────────────────────────────────────────
    REDIS_HOST: str = "localhost"
    REDIS_PORT: int = 6379
    REDIS_PASSWORD: str = ""

    # ── OpenAlex (academic search) ────────────────────────────────────────────
    OPENALEX_API_KEY: str = ""
    OPENALEX_MAILTO: str = ""  # recommended for "polite pool"


settings = Settings()